data = ':Hello:World:'.replace(':','-')
print(data)
print('-' * len(data))
print(abs(-3))
print('-' * len(str(abs(-3))))
print(bool(1))
print('-' * len(str(bool(1))))
print(bool(0))
print('-' * len(str(bool(0))))
